config/routes.rb
Goodlistens::Application.routes.draw do
  get "fb_share/auth", as: :fb_post

  get "fb_share/callback"

  get "fb_share/client"

  get "upload/index"

  post 'recommend', to: 'recommendation#send_recommendation', as: :recommend

  post "upload/uploadFile", as: :upload
  post 'upload/delete', as: :deleteFile
  post 'upload/rename', as: :renameFile

  get "rate_and_review/rate"
  get "rate_and_review/review"

  get "album/details", as: :album_details
  post 'album/review', to: 'rate_and_review#review', as: :album_review

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  match 'auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match 'track/trackdetails' => 'track#trackdetails', via: [:get, :post]

  get "login/index"
  get 'search', to: 'application#search', as: :search
  get 'details', to: 'application#details', as: :details
  post 'rate', to: 'rate_and_review#rate', as: :rate_album
  post 'album/review', to: 'rate_and_review#review', as: :review_album
  put 'album/review', to: 'rate_and_review#update', as: :update_review
  delete 'album/review', to: 'rate_and_review#destroy', as: :delete_review

  get 'home', to: 'users#index', as: :user
  get 'user/(:id)', to: 'users#other_user', as: :other_user
  get 'browse', to: 'users#newuser', as: :newuser
  put 'newuser/add_name', to: 'users#add_name', as: :add_name
  get 'newuser/more_info', to: 'users#more_info', as: :more_info
  post 'newuser/rate', to: 'rate_and_review#rate', as: :rate
  get 'newuser/next_albums', to: 'users#next_albums', as: :get_more
  get 'newuser/prev_albums', to: 'users#prev_albums', as: :get_less
  post 'user/addfriend', to: 'users#add_friend', as: :add_friend
  get 'lastfm_auth', to: 'users#lastfm_auth'
  put 'user/:id/update', to: 'users#update', as: :update_user

  get 'chat/:id', to: 'users#chat', as: :chat
  get 'chat', to: 'users#chat', as: :chat
  get 'initiate_chat', to: 'users#initiate_chat', as: :initiate_chat

  post 'track/trackdetails', to: 'track#trackdetails', as: :track_trackdetails

  root :to => 'application#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :remote_id
  has_many :reviews, :as => :reviewable 
  has_many :ratings, :as => :reviewable 
  validates :remote_id, presence: true, uniqueness: true
end

app/controllers/album_controller.rb
require 'sevendigital'
class AlbumController < ApplicationController
  def details
    client = Sevendigital::Client.new
    @album = client.release.get_details(params[:remote_id])
    album = Album.find_by_remote_id(@album.id)
    if album != nil
        @reviews = album.reviews.order('created_at DESC')
        @reviews.each do |r|
            if r.user == current_user
                @no_form = true
            end
        end
    end
    @review = Review.new
  end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/views/album/_reviews.html.erb
<% if r != nil %>
    <% if r.user.id != current_user.id %>
    <h3><%= r.title %></h3>
    <p><%= r.review %></p>
    <h3><small><a 
        <% if current_user.friends.include?(r.user) %>
            href='<%= other_user_path(r.user) %>'
        <% else %> 
            data-target='#addFriend<%= r.user.id %>'
        <% end %>
        data-toggle='modal'>
        <%= r.user.name %></a> - <%= r.created_at %></small></h3>
    <div class="modal fade" id='addFriend<%= r.user.id %>'>
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Add User as Friend</h4>
          </div>
          <div class="modal-body">
            <p>Do you want to add this user as a friend?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            <button type="button" class="btn btn-primary" id='yes<%= r.user.id %>' data-id='<%= r.user.id %>'>Yes</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    
    <script type="text/javascript">
        
        $('#addFriend<%= r.user.id %>').on('show.bs.modal', function(){
            <% if current_user.friends.include?(r.user) %>
                $('#addFriend<%= r.user.id %>').modal('hide');
            <% end %>
        });
        $('#yes<%= r.user.id %>').click(function(){
            var id = $(this).data('id');
            
            $.post('/user/addfriend?user_id='+id, function(){
                $('#addFriend<%= r.user.id %>').modal('hide');
                window.location = '/home';
            });
            channel.trigger('new_friend', {id: id});
        });
    </script>
    <% else %>
    <div id='user_review'>
        <h3 id='users_review_title'><%= r.title %></h3>
        <p id='users_review'><%= r.review %></p>
        <h3><small><%= r.user.name %> - <%= r.created_at.to_formatted_s(:short) %>
        <input type='hidden' name='album' id='review_id' value='<%= r.id %>'>
        <br/>
        <a href='#' class='btn btn-default edit' role='button' id='<%= r.id %>'>Edit</a>
        <a href='#' class='btn btn-default delete_review' role='button'>Delete</a>
        Share: </small><%= link_to image_tag('facebook_32.png'), fb_post_path(:title => 'Check out my review on goodlistens.com', :url => 'http://www.goodlistens.com'+request.fullpath, :desc => 'goodlistens: Review and share music') %>
        <a href="https://plus.google.com/share?url=valis.strangled.net:8080" onclick="javascript:window.open(this.href+window.location.pathname+window.location.search,
          '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">
          <img src="https://www.gstatic.com/images/icons/gplus-32.png" alt="Share on Google+"/></a></h3>
      </div>

    <% end %>
<% end %>

app/views/album/details.html.erb
<div class='container'>

    <h1><%=  @album.title %></h1>
    <div class='col-xs-12 col-md-7' >
        <%= image_tag(@album.image(500), :class=> 'img-responsive', :id=> 'image') %>
        
    </div>
    <input type='hidden' name='album' id='album_id' value='<%= @album.id %>'>
    <div class='col-md-5'>
        <h2><%= @album.artist.name %></h2>
        <% if user_signed_in? %> 
        
        <% end %>
        <ul class='list-unstyled tracks'>
            <% @album.get_tracks.each_with_index do |t, i| %>
                <li><%= (i+1).to_s + '. ' + t.title %></li>
            <% end %>
        </ul>
    </div>
    <div class='container' style='clear:both'>
        <% if user_signed_in? %>
        <h4 style='float:left;margin-right:10px' name='title'>Rate this album:</h4>
        <%= render '/stars_div', :i=>1 %>
                <% @rating = Rating.where(:user_id=>current_user, :reviewable_id=>Album.find_by_remote_id(@album.id)) %>
            <%= render '/rating_js', :rating => @rating[0], :i => 1, :album => @album %>
            <hr>
           
            <% if @no_form == nil %>
            <div id='review_form'>
                <div class='form-group'>
                    <label for='reviewTitle'>Title:</label>
                    <input type='text' class='form-control' name='title' id='reviewTitle'/>
                </div>
                <div class='form-group'>
                    <label for='reviewText'>Review:</label>
                    <textarea name='review' class='form-control' id='reviewText' cols='80' rows='4'></textarea>
                </div>
                <input type='hidden' name='album' id='album_id' value='<%= @album.id %>'>
                <button class='btn btn-primary submit-btn'>Submit</button> 
            </div>
            <% end %>
        <% end %>
        <div id='reviews'>
            <h4 id='review_header'>Reviews:</h4>
            <% if @reviews != nil %>
                <% @reviews.each do |r| %>
                    <%= render 'reviews', :r => r %>
                    <hr>
                <% end %>
            <% end %>
        </div>
        
    </div>



    <!-- Confirm file deletion -->
      <div class="modal fade" id='confirm_delete_dialog'>
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Delete review?</h4>
            </div>
            <div class="modal-body">
              <p id='modal_body'>Are you sure you want to delete?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
              <button type="button" class="btn btn-primary" id='delete_btn' data-id='1'>Yes</button>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->

    <!-- Recommendation dialog -->
    <div class="modal fade" id='recommendation_dialog'>
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Send Recommendation</h4>
          </div>
          <div class="modal-body">
            <h5>Select the friends that you want to send this recommendation to:</h5>
            <p id='modal_body'>
                <ul class='list-unstyled'>
                <% current_user.friends.each do |f| %>
                <li><input type='checkbox' class='friends' value='<%= f.id %>'> <%= f.name %></li>
                <% end %>
                </ul>
                Message: <input type='text' id='message' class='form-control'/>
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-primary" id='send-recommend' data-id='1'>Send</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>

app/views/album/reviews.js.erb
$('#reviews').html("<%=j render :partial=>'album/reviews' :collection=>@reviews %>");